In [4]:
import pandas as pd

In [5]:
dataframe = pd.read_csv(r'C:\Users\Spencer_Fox\Desktop\Iris.csv')

In [28]:
dataframe.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [32]:
dataframe.shape

(150, 6)

In [33]:
import nltk
import re 
from nltk.corpus import stopwords
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(dataframe)):
    print(i)
    title = re.sub('[^a-zA-Z]', ' ', dataframe['Species'][i])
    title = title.lower()
    title = title.split()
    
    title = [ps.stem(word) for word in title if not word in stopwords.words('english')]
    title = ' '.join(title)
    corpus.append(title)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149

In [34]:
corpus

['iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri setosa',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri versicolor',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica',
 'iri virginica']

# Bag of Words

In [35]:
from sklearn.feature_extraction.text import CountVectorizer


# Creating the bag of words

bow_article = CountVectorizer().fit(corpus)

count_tokens = bow_article.get_feature_names()

article_vect = bow_article.transform(corpus)
count_tokens

C:\Users\Spencer_Fox\Anaconda3\envs\main\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['iri', 'setosa', 'versicolor', 'virginica']

In [36]:
df_count_vect = pd.DataFrame(data=article_vect.toarray(), columns=count_tokens)
df_count_vect

     iri  setosa  versicolor  virginica
0      1       1           0          0
1      1       1           0          0
2      1       1           0          0
3      1       1           0          0
4      1       1           0          0
..   ...     ...         ...        ...
145    1       0           0          1
146    1       0           0          1
147    1       0           0          1
148    1       0           0          1
149    1       0           0          1

[150 rows x 4 columns]

# TFIDF

In [37]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
documentA = 'the man went out for a walk'
documentB = 'the children sat around the fire'

In [39]:
bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

In [40]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

In [41]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

In [42]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

# Term Frequency

In [43]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [44]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

# Inverse Data Frequency

In [45]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [46]:
idfs = computeIDF([numOfWordsA, numOfWordsB])

In [47]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [48]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])

In [49]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([documentA, documentB])
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)

C:\Users\Spencer_Fox\Anaconda3\envs\main\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

# N-gram analysis

In [50]:
from nltk.corpus import stopwords

def generate_ngrams(text, n_gram=1, stop = True):
    """
    Simple n-gram generator
    """
    
    stop = set(stopwords.words("english")) if stop else {}
    
    token = [
        token for token in text.lower().split(" ") if token != "" if token not in stop
    ]
    
    z = zip(*[token[i:] for i in range(n_gram)])
    ngrams = [" ".join(ngram) for ngram in z]
    
    return ngrams

# Create Unigrams

In [51]:
from collections import defaultdict

In [52]:
disaster_unigrams = defaultdict(int)
nondisaster_unigrams = defaultdict(int)

In [8]:
for Species in dataframe[dataframe.PetalLengthCm == 1].text:
    for word in generate_ngrams(Species):
        disaster_unigrams[word] += 1
        
for Species in dataframe[dataframe.PetalLengthCm == 0].text:
    for word in generate_ngrams[Species]:
        nondisaster_unigrams[word] += 1

AttributeError: 'DataFrame' object has no attribute 'text'